export const GET_ALL_ONBOARDING_LOADING = 'ONBOARDING_GET_ALL_ONBOARDING_LOADING';
export const GET_ALL_ONBOARDING_SUCCESS = 'ONBOARDING_GET_ALL_ONBOARDING_SUCCESS';
export const GET_ALL_ONBOARDING_FAILURE = 'ONBOARDING_GET_ALL_ONBOARDING_FAILURE';

export const UPDATE_ONBOARDING_LOADING = 'ONBOARDING_UPDATE_ONBOARDING_LOADING';
export const UPDATE_ONBOARDING_SUCCESS = 'ONBOARDING_UPDATE_ONBOARDING_SUCCESS';
export const UPDATE_ONBOARDING_FAILURE = 'ONBOARDING_UPDATE_ONBOARDING_FAILURE';
export const RESET_ERROR = 'ONBOARDING_RESET_ERROR';
