export const USAGE_GET_ALL_LOADING = 'PLANS_USAGE_GET_ALL_LOADING';
export const USAGE_GET_ALL_SUCCESS = 'PLANS_USAGE_GET_ALL_SUCCESS';
export const USAGE_GET_ALL_FAILURE = 'PLANS_USAGE_GET_ALL_FAILURE';
