export const GET_BILLING_LOADING = 'BILLING_GET_BILLING_LOADING';
export const GET_BILLING_SUCCESS = 'BILLING_GET_BILLING_SUCCESS';
export const GET_BILLING_FAILURE = 'BILLING_GET_BILLING_FAILURE';

export const GET_BILLING_INVOICES_LOADING ='BILLING_GET_BILLING_INVOICES_LOADING';
export const GET_BILLING_INVOICES_SUCCESS ='BILLING_GET_BILLING_INVOICES_SUCCESS';
export const GET_BILLING_INVOICES_FAILURE ='BILLING_GET_BILLING_INVOICES_FAILURE';

export const UPDATE_BILLING_LOADING = 'BILLING_UPDATE_BILLING_LOADING';
export const UPDATE_BILLING_SUCCESS = 'BILLING_UPDATE_BILLING_SUCCESS';
export const UPDATE_BILLING_FAILURE = 'BILLING_UPDATE_BILLING_FAILURE';

export const UPDATE_SUBSCRIPTION_LOADING = 'BILLING_UPDATE_SUBSCRIPTION_LOADING';
export const UPDATE_SUBSCRIPTION_SUCCESS = 'BILLING_UPDATE_SUBSCRIPTION_SUCCESS';
export const UPDATE_SUBSCRIPTION_FAILURE = 'BILLING_UPDATE_SUBSCRIPTION_FAILURE';

export const CANCEL_PLAN_LOADING = 'BILLING_CANCEL_PLAN_LOADING';
export const CANCEL_PLAN_SUCCESS = 'BILLING_CANCEL_PLAN_SUCCESS';
export const CANCEL_PLAN_FAILURE = 'BILLING_CANCEL_PLAN_FAILURE';
