export const PUSHER_CONNECTING = 'STREAM_PUSHER_CONNECTING';
export const PUSHER_CONNECTED = 'STREAM_PUSHER_CONNECTED';
export const PUSHER_CONNECTION_FAILED = 'STREAM_PUSHER_CONNECTION_FAILED';
export const PUSHER_CLOSING = 'STREAM_PUSHER_CLOSING';
export const PUSHER_CLOSED = 'STREAM_PUSHER_CLOSED';
export const PUSHER_CLOSE_FAILED = 'STREAM_PUSHER_CLOSE_FAILED';
