export const LOGOUT = 'AUTH_LOGOUT';
export const LOGIN_REFRESHING = 'AUTH_LOGIN_REFRESHING';
export const LOGIN_REFRESHED = 'AUTH_LOGIN_REFRESHED';
export const LOGIN_LOADING = 'AUTH_LOGIN_LOADING';
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
