export const RECORDING_START = 'STREAM_RECORDING_START';
export const RECORDING_STOPPED = 'STREAM_RECORDING_STOPPED';

export const RECORDING_FINALIZING = 'STREAM_RECORDING_FINALIZING';
export const RECORDING_UPLOADING = 'STREAM_RECORDING_UPLOADING';
export const RECORDING_UPLOADED = 'STREAM_RECORDING_UPLOADED';
export const RECORDING_UPLOAD_FAILED = 'STREAM_RECORDING_UPLOAD_FAILED';

export const RECORDING_RESET = 'STREAM_RECORDING_RESET';

export const RECORDING_UPDATE_TIMER = 'STREAM_RECORDING_UPDATE_TIMER';
