export const OPEN_RIGHT_PANE = 'APP_OPEN_RIGHT_PANE';
export const CLOSE_RIGHT_PANE = 'APP_CLOSE_RIGHT_PANE';
export const RESET_RIGHT_PANE = 'APP_RESET_RIGHT_PANE';
export const OPEN_LEFT_PANE = 'APP_OPEN_LEFT_PANE';
export const CLOSE_LEFT_PANE = 'APP_CLOSE_LEFT_PANE';
